
# GAME SETTINGS

WIDTH = 640
HEIGHT = 640
TILESIZE = 32
FPS = 60

PLAYER_LAYER = 4
CHARACTER_LAYER = 4
PATH_LAYER = 3
WALL_LAYER = 2
GROUND_LAYER = 1

PLAYER_SPEED = 3

# COLORS

RED = (255, 0, 0)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)

tilemap1 = [
    'WWWWWWWWWWWWWWWWWWWW',
    'W..................W',
    'W..................W',
    'W..................D',
    'W..................W',
    'W..................W',
    'W..................W',
    'W..................W',
    'W.........P........W',
    'W..............W...W',
    'W..................W',
    'W..................W',
    'W..................W',
    'WWWWWWWW......WWWWWW',
    'W..................W',
    'W..................W',
    'W..................W',
    'W..................W',
    'W..................W',
    'WWWWWWWWWWWWWWWWWDWW',
]

tilemap2 = [
    'FFFFFFFFFFFFFFFFFDFF',
    'FGGGGGGGGGGGGGGGGPGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FFFFFFFFFFFFFFFFFFFF',
]


tilemap3 = [
    'FFFFFFFFFFFFFFFFFFFF',
    'FGGGGGGGGGGGGGGGGPGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGWWWWWWWWWWWWWWWGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGWWWWWWWWWWWWGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FGGGGGGGGGGGGGGGGGGF',
    'FFFFFFFFFFFFFFFFFFFF',
]